# Builds docker image for gcp-synthea:
# Run using:
# $ gcloud builds submit --config cloudbuild.yaml --timeout 1h .
substitutions:
  _CUSTOM_TAG_NAME: 'latest'
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag=gcr.io/$PROJECT_ID/gcp-synthea:${_CUSTOM_TAG_NAME}'
      - '--file=docker/Dockerfile'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/gcp-synthea:${_CUSTOM_TAG_NAME}'
